/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import mundo.Comparador;

/**
 *
 * @author Cristian
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recibidorNumero = new javax.swing.JPanel();
        recibidor = new javax.swing.JTextField();
        ingresarNumero = new javax.swing.JButton();
        progresoNumeros = new javax.swing.JPanel();
        intentos = new javax.swing.JPanel();
        intentosTexto = new javax.swing.JLabel();
        intentosNumero = new javax.swing.JLabel();
        numerosInsertadosPreviamente = new javax.swing.JPanel();
        panelPuntosYcomas = new javax.swing.JPanel();
        puntosYComas = new javax.swing.JLabel();
        marcadorNumeros = new javax.swing.JPanel();
        botonUno = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonTres = new javax.swing.JButton();
        botonSiete = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonOcho = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        progresoComas = new javax.swing.JPanel();
        puntosYComasGenerados = new javax.swing.JPanel();
        panelInferior = new javax.swing.JPanel();
        ReiniciarJuego = new javax.swing.JButton();
        etiquetaNumeroDeCifras = new javax.swing.JLabel();
        numeroDeCifras = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de puntos y comas");

        recibidorNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("Escribir numero"));

        ingresarNumero.setText("Insertar número");
        ingresarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recibidorNumeroLayout = new javax.swing.GroupLayout(recibidorNumero);
        recibidorNumero.setLayout(recibidorNumeroLayout);
        recibidorNumeroLayout.setHorizontalGroup(
            recibidorNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recibidorNumeroLayout.createSequentialGroup()
                .addGroup(recibidorNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recibidorNumeroLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(recibidor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recibidorNumeroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(ingresarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        recibidorNumeroLayout.setVerticalGroup(
            recibidorNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recibidorNumeroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(recibidor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(ingresarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        progresoNumeros.setBorder(javax.swing.BorderFactory.createTitledBorder("Intentos realizados"));

        intentosTexto.setText("Intentos:");

        intentosNumero.setText("0");

        javax.swing.GroupLayout intentosLayout = new javax.swing.GroupLayout(intentos);
        intentos.setLayout(intentosLayout);
        intentosLayout.setHorizontalGroup(
            intentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intentosTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intentosNumero)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        intentosLayout.setVerticalGroup(
            intentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intentosTexto)
                    .addComponent(intentosNumero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        numerosInsertadosPreviamente.setLayout(new java.awt.GridLayout(7, 3));

        javax.swing.GroupLayout progresoNumerosLayout = new javax.swing.GroupLayout(progresoNumeros);
        progresoNumeros.setLayout(progresoNumerosLayout);
        progresoNumerosLayout.setHorizontalGroup(
            progresoNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(numerosInsertadosPreviamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        progresoNumerosLayout.setVerticalGroup(
            progresoNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progresoNumerosLayout.createSequentialGroup()
                .addComponent(numerosInsertadosPreviamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPuntosYcomas.setBorder(javax.swing.BorderFactory.createTitledBorder("Puntos y comas"));

        puntosYComas.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        javax.swing.GroupLayout panelPuntosYcomasLayout = new javax.swing.GroupLayout(panelPuntosYcomas);
        panelPuntosYcomas.setLayout(panelPuntosYcomasLayout);
        panelPuntosYcomasLayout.setHorizontalGroup(
            panelPuntosYcomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosYcomasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(puntosYComas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPuntosYcomasLayout.setVerticalGroup(
            panelPuntosYcomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosYcomasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(puntosYComas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        marcadorNumeros.setBorder(javax.swing.BorderFactory.createTitledBorder("Marcar números no incluidos"));

        botonUno.setBackground(new java.awt.Color(204, 204, 204));
        botonUno.setText("1");
        botonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnoActionPerformed(evt);
            }
        });

        botonSeis.setBackground(new java.awt.Color(204, 204, 204));
        botonSeis.setText("6");
        botonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeisActionPerformed(evt);
            }
        });

        botonDos.setBackground(new java.awt.Color(204, 204, 204));
        botonDos.setText("2");
        botonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDosActionPerformed(evt);
            }
        });

        botonTres.setBackground(new java.awt.Color(204, 204, 204));
        botonTres.setText("3");
        botonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTresActionPerformed(evt);
            }
        });

        botonSiete.setBackground(new java.awt.Color(204, 204, 204));
        botonSiete.setText("7");
        botonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSieteActionPerformed(evt);
            }
        });

        botonCuatro.setBackground(new java.awt.Color(204, 204, 204));
        botonCuatro.setText("4");
        botonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuatroActionPerformed(evt);
            }
        });

        botonNueve.setBackground(new java.awt.Color(204, 204, 204));
        botonNueve.setText("9");
        botonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNueveActionPerformed(evt);
            }
        });

        botonCinco.setBackground(new java.awt.Color(204, 204, 204));
        botonCinco.setText("5");
        botonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCincoActionPerformed(evt);
            }
        });

        botonOcho.setBackground(new java.awt.Color(204, 204, 204));
        botonOcho.setText("8");
        botonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOchoActionPerformed(evt);
            }
        });

        botonCero.setBackground(new java.awt.Color(204, 204, 204));
        botonCero.setText("0");
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout marcadorNumerosLayout = new javax.swing.GroupLayout(marcadorNumeros);
        marcadorNumeros.setLayout(marcadorNumerosLayout);
        marcadorNumerosLayout.setHorizontalGroup(
            marcadorNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcadorNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(marcadorNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(marcadorNumerosLayout.createSequentialGroup()
                        .addComponent(botonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(marcadorNumerosLayout.createSequentialGroup()
                        .addComponent(botonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(botonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        marcadorNumerosLayout.setVerticalGroup(
            marcadorNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcadorNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(marcadorNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(marcadorNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        progresoComas.setBorder(javax.swing.BorderFactory.createTitledBorder("progreso"));

        puntosYComasGenerados.setLayout(new java.awt.GridLayout(7, 3));

        javax.swing.GroupLayout progresoComasLayout = new javax.swing.GroupLayout(progresoComas);
        progresoComas.setLayout(progresoComasLayout);
        progresoComasLayout.setHorizontalGroup(
            progresoComasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puntosYComasGenerados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        progresoComasLayout.setVerticalGroup(
            progresoComasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puntosYComasGenerados, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        ReiniciarJuego.setText("ReiniciarJuego");
        ReiniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarJuegoActionPerformed(evt);
            }
        });

        etiquetaNumeroDeCifras.setText("número de cifras a jugar");

        numeroDeCifras.setMaximumRowCount(9);
        numeroDeCifras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        numeroDeCifras.setSelectedIndex(2);
        numeroDeCifras.setToolTipText("");
        numeroDeCifras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDeCifrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReiniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(etiquetaNumeroDeCifras)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroDeCifras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                .addComponent(etiquetaNumeroDeCifras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroDeCifras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addComponent(ReiniciarJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPuntosYcomas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marcadorNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progresoComas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progresoNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recibidorNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPuntosYcomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcadorNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progresoComas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recibidorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progresoNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnoActionPerformed
        if(contadorUno==0){
            botonUno.setBackground(java.awt.Color.red);
            contadorUno=1;
        }
        else{
            botonUno.setBackground(new java.awt.Color(204,204,204));
            contadorUno = 0;
        }
    }//GEN-LAST:event_botonUnoActionPerformed
   
    private void ingresarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarNumeroActionPerformed
        miComparador.setNumeroActual(Integer.parseInt(recibidor.getText()));
        puntosYComas.setText(miComparador.puntosYComas());
        numerosInsertadosPreviamente.add(new javax.swing.JLabel(recibidor.getText()));
        javax.swing.JLabel theLabel = new javax.swing.JLabel(miComparador.puntosYComas());
        theLabel.setFont(new java.awt.Font(theLabel.getFont().getFontName(), theLabel.getFont().getStyle(), 32));
        puntosYComasGenerados.add(theLabel);
        numerosInsertadosPreviamente.updateUI();
        puntosYComasGenerados.updateUI();
        if(miComparador.puntosYComas().equals(miComparador.determinarGanardor())){
            javax.swing.JOptionPane.showMessageDialog(null, "has ganado");   
        }
        intentosNumero.setText(Integer.parseInt(intentosNumero.getText())+1+"");
        
    }//GEN-LAST:event_ingresarNumeroActionPerformed

    private void botonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDosActionPerformed
        if(contadorDos==0){
            botonDos.setBackground(java.awt.Color.red);
            contadorDos=1;
        }
        else{
            botonDos.setBackground(new java.awt.Color(204,204,204));
            contadorDos = 0;
        }
    }//GEN-LAST:event_botonDosActionPerformed

    private void botonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTresActionPerformed
        if(contadorTres==0){
            botonTres.setBackground(java.awt.Color.red);
            contadorTres=1;
        }
        else{
            botonTres.setBackground(new java.awt.Color(204,204,204));
            contadorTres = 0;
        }
    }//GEN-LAST:event_botonTresActionPerformed

    private void botonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuatroActionPerformed
        if(contadorCuatro==0){
            botonUno.setBackground(java.awt.Color.red);
            contadorCuatro=1;
        }
        else{
            botonUno.setBackground(new java.awt.Color(204,204,204));
            contadorCuatro = 0;
        }
    }//GEN-LAST:event_botonCuatroActionPerformed

    private void botonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCincoActionPerformed
        if(contadorCinco==0){
            botonCinco.setBackground(java.awt.Color.red);
            contadorCinco=1;
        }
        else{
            botonCinco.setBackground(new java.awt.Color(204,204,204));
            contadorCinco = 0;
        }
    }//GEN-LAST:event_botonCincoActionPerformed

    private void botonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeisActionPerformed
        if(contadorSeis==0){
            botonSeis.setBackground(java.awt.Color.red);
            contadorSeis=1;
        }
        else{
            botonSeis.setBackground(new java.awt.Color(204,204,204));
            contadorSeis = 0;
        }
    }//GEN-LAST:event_botonSeisActionPerformed

    private void botonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSieteActionPerformed
        if(contadorSiete==0){
            botonSiete.setBackground(java.awt.Color.red);
            contadorSiete=1;
        }
        else{
            botonSiete.setBackground(new java.awt.Color(204,204,204));
            contadorSiete = 0;
        }
    }//GEN-LAST:event_botonSieteActionPerformed

    private void botonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOchoActionPerformed
       if(contadorOcho==0){
            botonOcho.setBackground(java.awt.Color.red);
            contadorOcho=1;
        }
        else{
            botonOcho.setBackground(new java.awt.Color(204,204,204));
            contadorOcho = 0;
        }
    }//GEN-LAST:event_botonOchoActionPerformed

    private void botonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNueveActionPerformed
        if(contadorNueve==0){
            botonNueve.setBackground(java.awt.Color.red);
            contadorNueve=1;
        }
        else{
            botonNueve.setBackground(new java.awt.Color(204,204,204));
            contadorNueve = 0;
        }
    }//GEN-LAST:event_botonNueveActionPerformed

    private void botonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCeroActionPerformed
       if(contadorCero==0){
            botonCero.setBackground(java.awt.Color.red);
            contadorCero=1;
        }
        else{
            botonCero.setBackground(new java.awt.Color(204,204,204));
            contadorCero = 0;
        }
    }//GEN-LAST:event_botonCeroActionPerformed

    private void ReiniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarJuegoActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null, miComparador.getNumeroObjetivo());
        dispose();
        main(null);
    }//GEN-LAST:event_ReiniciarJuegoActionPerformed

    private void numeroDeCifrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDeCifrasActionPerformed
       miComparador.setNumeroDeCifras(Integer.parseInt((String)numeroDeCifras.getSelectedItem()));
       miComparador.setNumeroObjetivo(miComparador.getElGenerador().generarNumero(miComparador.getNumeroDeCifras()));
       
    }//GEN-LAST:event_numeroDeCifrasActionPerformed
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReiniciarJuego;
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonCinco;
    private javax.swing.JButton botonCuatro;
    private javax.swing.JButton botonDos;
    private javax.swing.JButton botonNueve;
    private javax.swing.JButton botonOcho;
    private javax.swing.JButton botonSeis;
    private javax.swing.JButton botonSiete;
    private javax.swing.JButton botonTres;
    private javax.swing.JButton botonUno;
    private javax.swing.JLabel etiquetaNumeroDeCifras;
    private javax.swing.JButton ingresarNumero;
    private javax.swing.JPanel intentos;
    private javax.swing.JLabel intentosNumero;
    private javax.swing.JLabel intentosTexto;
    private javax.swing.JPanel marcadorNumeros;
    private javax.swing.JComboBox<String> numeroDeCifras;
    private javax.swing.JPanel numerosInsertadosPreviamente;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPuntosYcomas;
    private javax.swing.JPanel progresoComas;
    private javax.swing.JPanel progresoNumeros;
    private javax.swing.JLabel puntosYComas;
    private javax.swing.JPanel puntosYComasGenerados;
    private javax.swing.JTextField recibidor;
    private javax.swing.JPanel recibidorNumero;
    // End of variables declaration//GEN-END:variables
    private Comparador miComparador = new Comparador();
    private int contadorUno = 0;
    private int contadorDos = 0;
    private int contadorTres = 0;
    private int contadorCuatro = 0;
    private int contadorCinco = 0;
    private int contadorSeis = 0;
    private int contadorSiete = 0;
    private int contadorOcho = 0;
    private int contadorNueve = 0;
    private int contadorCero = 0;
}

